CREATE	SCHEMA PHARMNETWORK;
CREATE TABLE PHARMNETWORK.PHARMACY
(
   PH_ID SERIAl PRIMARY KEY,
   address varchar(40)
);
CREATE TABLE PHARMNETWORK."GROUP"
(
GR_ID serial PRIMARY KEY,
name varchar(40)
);
CREATE TABLE PHARMNETWORK.PREPARATION
(
R_ID serial PRIMARY KEY,
GR_ID int2 REFERENCES PHARMNETWORK.GROUP(GR_ID),
Name varcher(40)
);
CREATE TABLE PHARMNETWORK.AVAILABILITY
(
A_ID serial PRIMARY KEY,
PH_ID int2 REFERENCES PHARMNETWORK.PHARMACY(PH_ID),
PH_ID int2 REFERENCES PHARMNETWORK.PREPARATION(PH_ID),
Quantity int2
DateEnd Date
)
CREATE TABLE PHARMNETWORK.DEFICIT
(
D_ID serial PRIMARY KEY,
PH_ID int2 REFERENCES PHARMACY(PH_ID),
PH_ID int2 REFERENCES PREPARATION(PH_ID),
Solution varchar(40),
dateStop Date NOT NULL
)
CREATE TABLE PHARMNETWORK.Employee
(
E_ID serial PRIMARY KEY,
PH_ID int2 REFERENCES PHARMNETWORK.PHARMACY(PH_ID),
FName varchar(40) имя сотрудника,
Post varchar(40) должность,
)
CREATE TABLE PHARMNETWORK.CLIENT
(
C_ID serial PRIMARY KEY,
FName varchar(40) Имя клиента,
LName varchar(40) Фамилия клиента,
DateReg DATE Дата регистрации NOT NULL,
)
CREATE TABLE PHARMNETWORK.BASKET
(
BS_ID serial PRIMARY KEY,
E_ID int2 REFERENCES PHARMNETWORK.PHARMACY(PH_ID),
C_ID int2 REFERENCES PHARMNETWORK.CLIENT(C_ID),
)
CREATE TABLE PHARMNETWORK.BUYING
(
B_ID serial PRIMARY KEY,
PH_ID int2 REFERENCES PHARMNETWORK.PHARMACY(PH_ID),
PR_ID int2 REFERENCES PREPARATION(PH_ID),
BS_ID int2 REFERENCES PHARMNETWORK.BASKET(BS_ID),
Price money,
)